name = "cloudflare-redirect"
compatibility_date = "2024-03-01"
compatibility_flags = ["nodejs_compat"]

[build]
main = "src/worker/_worker.js"

[env.production]
name = "cloudflare-redirect"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
head_sampling_rate = 0.9

